apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/managed-by-location: url:https://acdp-acdp-backstageassetbucketconstructcmkencrypte-cnkmdtejc5bh.s3.us-west-2.amazonaws.com/backstage/catalog/acdp/component/auth-setup/catalog-info.yaml
    backstage.io/managed-by-origin-location: url:https://acdp-acdp-backstageassetbucketconstructcmkencrypte-cnkmdtejc5bh.s3.us-west-2.amazonaws.com/backstage/catalog/acdp/component/auth-setup/catalog-info.yaml
    backstage.io/view-url: https://acdp-acdp-backstageassetbucketconstructcmkencrypte-cnkmdtejc5bh.s3.us-west-2.amazonaws.com/backstage/catalog/acdp/component/auth-setup/catalog-info.yaml
    aws.amazon.com/acdp-deploy-on-create: "true"
    aws.amazon.com/acdp-deployment-target: default
    aws.amazon.com/techdocs-builder: external
    backstage.io/techdocs-ref: dir:.
    aws.amazon.com/template-entity-ref: template:default/auth-setup
    aws.amazon.com/acdp-assets-ref: dir:assets/
    aws.amazon.com/acdp-assets-stored: "true"
    backstage.io/source-location: url:https://acdp-acdp-backstageassetbucketconstructcmkencrypte-cnkmdtejc5bh.s3.us-west-2.amazonaws.com/backstage/catalog/acdp/component/auth-setup/assets/
    aws.amazon.com/ops-metrics/my-application-arn: arn_goes_here
  description: A CDK Python app for deploying a customizable but structured OAuth
    configuration, with optional Cognito infrastructure to populate this
    configuration.
  name: auth-setup
  namespace: acdp
  uid: a47db924-e3da-4123-b7bb-206fefd369cf
  etag: 8e8490e910b84c2717ef5bc7dd08cdf0e0727ca5
relations:
  - type: ownedBy
    targetRef: group:default/asdf
    target:
      kind: group
      namespace: default
      name: asdf
spec:
  lifecycle: experimental
  owner: group:default/asdf
  type: infrastructure
