apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:../docs/components/cms-auth/
  description: A CDK Python app for authenticating CMS users and services
  name: cms-auth
  tags:
  - cms
  - auth
  - authorization-code
  - token-validation
  title: CMS Auth Module
spec:
  output:
    links:
    - entityRef: ${{ steps.catalogRegister.output.entityRef }}
      icon: catalog
      title: Open in catalog
  owner: aws solutions
  parameters:
  - properties:
      componentId:
        default: cms-auth
        description: Unique name of the component
        pattern: '[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z]'
        title: Name
        type: string
        ui:field: EntityNamePicker
      description:
        default: A CDK Python app for authenticating CMS users and services
        description: Help others understand what this component is for.
        title: Description
        type: string
      owner:
        description: Owner of the component
        title: Owner
        type: string
        ui:field: OwnerPicker
        ui:options:
          catalogFilter:
            kind:
            - Group
            - User
    required:
    - componentId
    - owner
    title: Provide the required information
  - properties:
      appUniqueId:
        default: cms
        description: Application unique identifier used to uniquely name resources within the stack
        title: App Unique ID
        type: string
        ui:disabled: true
    required:
    - appUniqueId
    title: Provide the Module Configuration
  steps:
  - action: aws:acdp:catalog:create
    id: acdpCatalogCreate
    input:
      assetsSourcePath: dir:../acdp/cms-auth/
      componentId: ${{ parameters.componentId }}
      docsSiteSourcePath: dir:../docs/components/cms-auth/site/
      entity:
        apiVersion: backstage.io/v1alpha1
        kind: Component
        metadata:
          annotations:
            aws.amazon.com/acdp-deploy-on-create: 'true'
          description: ${{parameters.description}}
          name: ${{parameters.componentId}}
          namespace: acdp
        spec:
          lifecycle: experimental
          owner: ${{parameters.owner}}
          type: service
    name: ACDP S3 Catalog Create
  - action: catalog:register
    id: catalogRegister
    input:
      catalogInfoUrl: ${{ steps.acdpCatalogCreate.output.catalogItemS3Url }}
    name: Backstage Catalog Register
  - action: aws:acdp:configure
    id: acdpConfigureDeploy
    input:
      buildParameters:
      - name: CFN_TEMPLATE_URL
        value: https://acdp-assets-025790976786-us-east-1.s3.amazonaws.com/connected-mobility-solution-on-aws/v1.1.4/cms-auth/cms-auth.template
      - name: APP_UNIQUE_ID
        value: ${{ parameters.appUniqueId }}
      entityRef: ${{ steps.catalogRegister.output.entityRef }}
    name: ACDP Configure Deploy
  type: service
