version: 0.2

phases:
  build:
    commands:
      # Build and deploy
      - git clone https://github.com/mttwise/backstage-sample-module
      - cd backstage-sample-module
      - |
        aws cloudformation deploy \
        --stack-name ${MODULE_STACK_NAME} \
        --template-file ./sample-cfn.template \
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
        --role-arn "${CLOUDFORMATION_ROLE_ARN}"
