version: 0.2

phases:
  build:
    commands:
      # Build and deploy
      - echo "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - echo "$CODEBUILD_SOURCE_REPO_URL"
      - echo "$CODEBUILD_SRC_DIR"
      - pwd
      - ls
      - cd "$CODEBUILD_SRC_DIR"
      - ls
      - |
      aws cloudformation deploy \
  		--stack-name ${MODULE_STACK_NAME} \
  		--template-file ./sample-cfn.template \
  		--capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
      --role-arn "${CLOUDFORMATION_ROLE_ARN}"
