apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  description: sample
  name: backstage-sample-2
  tags:
  - guide
  - sample
  title: Backstage Sample Module 2
spec:
  type: service
  output:
    links:
    - entityRef: ${{ steps.catalogRegister.output.entityRef }}
      icon: catalog
      title: Open in catalog
  owner: aws solutions
  parameters:
  - properties:
      componentId:
        default: backstage-sample-2
        description: Unique name of the component
        pattern: '[a-zA-Z][-a-zA-Z0-9]*[a-zA-Z]'
        title: Name
        type: string
        ui:field: EntityNamePicker
      description:
        default: sample
        description: Help others understand what this component is for.
        title: Description
        type: string
      owner:
        description: Owner of the component
        title: Owner
        type: string
        ui:field: OwnerPicker
        ui:options:
          catalogFilter:
            kind:
            - Group
            - User
    required:
    - componentId
    - owner
    title: Provide the required information
  - properties:
      appName:
        default: sample-app
        description: App name
        title: App Name
        type: string
    required:
    - appName
    title: Provide the Module Configuration
  steps:
  - action: aws:acdp:catalog:create
    id: acdpCatalogCreate
    name: ACDP S3 Catalog Create
    input:
      componentId: ${{ parameters.componentId }}
      entity:
        apiVersion: backstage.io/v1alpha1
        kind: Component
        metadata:
          annotations:
            aws.amazon.com/acdp-deploy-on-create: "true"
            aws.amazon.com/acdp-deploy-buildspec: url:https://github.com/mttwise/backstage-sample-module/blob/main/.acdp/deploy2.buildspec.yaml
            aws.amazon.com/acdp-teardown-buildspec: url:https://github.com/mttwise/backstage-sample-module/blob/main/.acdp/teardown.buildspec.yaml
            backstage.io/techdocs-ref: dir:.
          description: ${{parameters.description}}
          name: ${{parameters.componentId}}
          namespace: samples
        spec:
          lifecycle: experimental
          owner: ${{parameters.owner}}
          type: service

  - action: catalog:register
    id: catalogRegister
    name: Backstage Catalog Register
    input:
      catalogInfoUrl: ${{ steps.acdpCatalogCreate.output.catalogItemS3Url }}

  - action: aws:acdp:configure
    id: acdpConfigureDeploy
    name: ACDP Configure Deploy
    input:
      entityRef: ${{ steps.catalogRegister.output.entityRef }}
      buildParameters:
      - name: APP_NAME
        value: sample2

