docs_dir: ./docs
nav:
- Home: index.md
plugins:
- techdocs-core
repo_name: GitHub
repo_url: https://github.com/mttwise/backstage-sample-module
site_author: mttwise
site_description: A sample backstage module
site_dir: ./site
site_name: backstage-sample
site_url: https://example.com
theme:
  name: readthedocs
